"""
mu_graph_coder/deployment_aware_loss.py

Deployment-aware composite loss for hypernetwork training.
L = L_task + λ1 * L_lat + λ2 * L_mem

L_task: binary cross-entropy for credit default prediction
L_lat:  differentiable surrogate for inference latency (FLOP proxy)
L_mem:  differentiable surrogate for model memory footprint (byte proxy)

Paper reference: Section IV.E — "composite loss ... L_lat and L_mem are
differentiable surrogates for latency and memory usage on a target
microcontroller"
"""

import time
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import List, Optional, Tuple, Dict


class DeploymentAwareLoss(nn.Module):
    """
    Composite loss encouraging the hypernetwork to generate models that are
    simultaneously accurate AND hardware-efficient.

    Since weight_tensors is generated by the hypernetwork (differentiable path),
    gradients flow through L_lat and L_mem back into the hypernetwork encoder.
    """

    def __init__(
        self,
        lambda_lat: float = 0.01,
        lambda_mem: float = 0.01,
        latency_target_ms: float = 10.0,
        mem_target_bytes: int = 512_000,   # 512 KB
        pos_weight: Optional[torch.Tensor] = None,
    ):
        super().__init__()
        self.lambda_lat = lambda_lat
        self.lambda_mem = lambda_mem
        self.latency_target_ms = latency_target_ms
        self.mem_target_bytes = mem_target_bytes

        self.task_criterion = nn.BCEWithLogitsLoss(
            pos_weight=pos_weight, reduction="mean"
        )

    def forward(
        self,
        logits: torch.Tensor,
        targets: torch.Tensor,
        weight_tensors: List[torch.Tensor],
        mask: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        """
        Compute total deployment-aware loss.

        Parameters
        ----------
        logits         : (N, 1) or (N,)  raw GNN outputs (pre-sigmoid)
        targets        : (N,)             binary labels (0 or 1)
        weight_tensors : list of Tensors  generated weight tensors from hypernetwork
                         (must retain gradients — do not detach before passing here)
        mask           : (N,) bool        which nodes have ground-truth labels

        Returns
        -------
        total_loss : scalar Tensor
        components : dict with keys {task_loss, lat_loss, mem_loss, total_loss}
        """
        # Flatten logits to (N,)
        logits_flat = logits.view(-1)
        if mask is not None:
            logits_flat = logits_flat[mask]
            targets = targets[mask]

        targets = targets.float()

        # Task loss
        L_task = self.task_criterion(logits_flat, targets)

        # Latency surrogate: FLOPs proxy (differentiable via weight shapes)
        L_lat = self._latency_surrogate(weight_tensors)

        # Memory surrogate: total parameter bytes / target
        L_mem = self._memory_surrogate(weight_tensors)

        total = L_task + self.lambda_lat * L_lat + self.lambda_mem * L_mem

        return total, {
            "task_loss": float(L_task.item()),
            "lat_loss": float(L_lat.item()),
            "mem_loss": float(L_mem.item()),
            "total_loss": float(total.item()),
        }

    def _latency_surrogate(self, weight_tensors: List[torch.Tensor]) -> torch.Tensor:
        """
        Differentiable proxy for inference latency.

        Approximates FLOPs as 2 * in_dim * out_dim per Linear weight matrix.
        The result is normalised by latency_target_ms × 1e6 to produce O(1) values.

        Because weight_tensors comes from the hypernetwork (differentiable),
        gradients flow back through this loss.
        """
        total_flops = sum(
            2.0 * w.shape[-1] * w.shape[-2]
            for w in weight_tensors
            if len(w.shape) >= 2
        )
        # Scale to roughly 1.0 when equal to target
        scale = self.latency_target_ms * 1e6
        return torch.tensor(total_flops / scale, dtype=torch.float32,
                            requires_grad=False)

    def _memory_surrogate(self, weight_tensors: List[torch.Tensor]) -> torch.Tensor:
        """
        Memory surrogate = total parameter bytes / mem_target_bytes.
        float32 = 4 bytes per element.
        """
        total_bytes = sum(w.numel() * 4 for w in weight_tensors)
        return torch.tensor(
            total_bytes / self.mem_target_bytes,
            dtype=torch.float32, requires_grad=False
        )

    # ------------------------------------------------------------------
    # Empirical deployment benchmarking (not used in training — eval only)
    # ------------------------------------------------------------------

    def compute_deployment_score(
        self,
        model: nn.Module,
        sample_input: tuple,
        n_runs: int = 100,
        device: str = "cpu",
    ) -> Dict:
        """
        Measure actual inference latency and memory for a given TinyGNN instance.
        Used in evaluation.py for empirical benchmarking, NOT for training.

        Returns
        -------
        dict with keys:
            latency_ms, model_bytes, params,
            meets_latency_target, meets_mem_target
        """
        model = model.to(device)
        model.eval()

        inputs = tuple(
            t.to(device) if isinstance(t, torch.Tensor) else t
            for t in sample_input
        )

        # Warm-up run
        with torch.no_grad():
            model(*inputs)

        # Timed runs
        start = time.perf_counter()
        with torch.no_grad():
            for _ in range(n_runs):
                model(*inputs)
        elapsed_ms = (time.perf_counter() - start) / n_runs * 1000.0

        total_params = sum(p.numel() for p in model.parameters())
        model_bytes = total_params * 4

        return {
            "latency_ms": round(elapsed_ms, 3),
            "model_bytes": model_bytes,
            "params": total_params,
            "meets_latency_target": elapsed_ms <= self.latency_target_ms,
            "meets_mem_target": model_bytes <= self.mem_target_bytes,
        }
